const userConstant = {
  LOAD_USERS_SUCCESS: 'LOAD_USERS_SUCCESS',
  GET_USER_DETAIL: 'GET_USER_DETAIL',
  UPDATE_USER_AUTH: 'UPDATE_USER_AUTH',
  CREATE_USER: 'CREATE_USER',
  REMOVE_USER: 'REMOVE_USER',
}

export default userConstant
